require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AuthorshipsController do

  # This should return the minimal set of attributes required to create a valid
  # Authorship. As you add validations to Authorship, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AuthorshipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all authorships as @authorships" do
      authorship = Authorship.create! valid_attributes
      get :index, {}, valid_session
      assigns(:authorships).should eq([authorship])
    end
  end

  describe "GET show" do
    it "assigns the requested authorship as @authorship" do
      authorship = Authorship.create! valid_attributes
      get :show, {:id => authorship.to_param}, valid_session
      assigns(:authorship).should eq(authorship)
    end
  end

  describe "GET new" do
    it "assigns a new authorship as @authorship" do
      get :new, {}, valid_session
      assigns(:authorship).should be_a_new(Authorship)
    end
  end

  describe "GET edit" do
    it "assigns the requested authorship as @authorship" do
      authorship = Authorship.create! valid_attributes
      get :edit, {:id => authorship.to_param}, valid_session
      assigns(:authorship).should eq(authorship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Authorship" do
        expect {
          post :create, {:authorship => valid_attributes}, valid_session
        }.to change(Authorship, :count).by(1)
      end

      it "assigns a newly created authorship as @authorship" do
        post :create, {:authorship => valid_attributes}, valid_session
        assigns(:authorship).should be_a(Authorship)
        assigns(:authorship).should be_persisted
      end

      it "redirects to the created authorship" do
        post :create, {:authorship => valid_attributes}, valid_session
        response.should redirect_to(Authorship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved authorship as @authorship" do
        # Trigger the behavior that occurs when invalid params are submitted
        Authorship.any_instance.stub(:save).and_return(false)
        post :create, {:authorship => {}}, valid_session
        assigns(:authorship).should be_a_new(Authorship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Authorship.any_instance.stub(:save).and_return(false)
        post :create, {:authorship => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested authorship" do
        authorship = Authorship.create! valid_attributes
        # Assuming there are no other authorships in the database, this
        # specifies that the Authorship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Authorship.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => authorship.to_param, :authorship => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested authorship as @authorship" do
        authorship = Authorship.create! valid_attributes
        put :update, {:id => authorship.to_param, :authorship => valid_attributes}, valid_session
        assigns(:authorship).should eq(authorship)
      end

      it "redirects to the authorship" do
        authorship = Authorship.create! valid_attributes
        put :update, {:id => authorship.to_param, :authorship => valid_attributes}, valid_session
        response.should redirect_to(authorship)
      end
    end

    describe "with invalid params" do
      it "assigns the authorship as @authorship" do
        authorship = Authorship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Authorship.any_instance.stub(:save).and_return(false)
        put :update, {:id => authorship.to_param, :authorship => {}}, valid_session
        assigns(:authorship).should eq(authorship)
      end

      it "re-renders the 'edit' template" do
        authorship = Authorship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Authorship.any_instance.stub(:save).and_return(false)
        put :update, {:id => authorship.to_param, :authorship => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested authorship" do
      authorship = Authorship.create! valid_attributes
      expect {
        delete :destroy, {:id => authorship.to_param}, valid_session
      }.to change(Authorship, :count).by(-1)
    end

    it "redirects to the authorships list" do
      authorship = Authorship.create! valid_attributes
      delete :destroy, {:id => authorship.to_param}, valid_session
      response.should redirect_to(authorships_url)
    end
  end

end
